name: CI/CD Pipeline for Robot Shop Microservices

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl config view

      - name: Set Up Helm
        uses: azure/setup-helm@v4.1.0

      - name: Helm Deploy
        run: |
          helm upgrade --install robot-shop ./K8s/helm -n robot-shop --create-namespace
          kubectl rollout status deployment/web -n robot-shop
